export const HERMES_CONTRACT_CORPUS_VERSION = 1
export const HERMES_CONTRACT_SENTINEL = 'must-not-survive-normalization'

export const hermesContractCorpus = {
  publicStatus: {
    version: '0.20.0',
    release_date: '2026.8.3',
    overall: 'ok',
    active_sessions: 2,
    gateway_running: true,
    gateway_state: 'running',
    gateway_busy: false,
    gateway_drainable: true,
    active_agents: 1,
    auth_required: true,
    auth_providers: ['local'],
    auth_flows: ['password'],
    components: {
      gateway: { status: 'ok', state: 'running' },
      storage: { status: 'degraded', state: 'slow' },
    },
    internal_path: HERMES_CONTRACT_SENTINEL,
  },
  authProviders: {
    providers: [
      { name: 'local', display_name: 'Local account', supports_password: true, client_secret: HERMES_CONTRACT_SENTINEL },
      { name: '', display_name: 'invalid' },
    ],
  },
  identity: {
    user_id: 'owner',
    email: 'owner@example.invalid',
    display_name: 'Owner',
    org_id: 'local',
    provider: 'local',
    expires_at: 1_800_000_000,
    token: HERMES_CONTRACT_SENTINEL,
  },
  wsTicket: { ticket: 'fixture-ticket.abc_123', expires_in: 30 },
  systemStats: {
    os: 'Linux', os_release: '6.8', platform: 'linux', arch: 'x86_64', hostname: 'hermes',
    python_version: '3.12', hermes_version: '0.20.0', cpu_count: 8, cpu_percent: 12.5, uptime_seconds: 300,
    memory: { total: 100, used: 40, available: 60, percent: 40 },
    disk: { total: 200, used: 80, free: 120, percent: 40 },
    process: { pid: 42, rss: 1234, num_threads: 9 },
    environment: HERMES_CONTRACT_SENTINEL,
  },
  modelOptions: {
    model: 'model-a',
    provider: 'provider-a',
    providers: [{
      authenticated: true,
      capabilities: { 'model-a': { fast: true, reasoning: true } },
      featured_models: ['model-a'],
      models: ['model-a', 'model-b', 'model-a'],
      name: 'Provider A',
      slug: 'provider-a',
      unavailable_models: ['model-z'],
      access_token: HERMES_CONTRACT_SENTINEL,
    }],
  },
  storedMessage: {
    id: 7,
    role: 'assistant',
    content: [{ type: 'text', text: 'Hello ' }, { type: 'text', text: 'Workbench' }],
    timestamp: 1_800_000_001,
  },
  gatewayLines: [
    JSON.stringify({ jsonrpc: '2.0', id: 'workbench-1', result: { session_id: 'session-1' } }),
    JSON.stringify({ jsonrpc: '2.0', id: 'workbench-2', error: { message: 'fixture failure' } }),
    JSON.stringify({ jsonrpc: '2.0', method: 'message.delta', params: { session_id: 'session-1', payload: { text: 'hello' } } }),
    JSON.stringify({ type: 'reasoning.end', session_id: 'session-1', payload: { text: 'done' } }),
    '{not-json',
  ].join('\n'),
  toolStart: {
    type: 'tool.start', session_id: 'session-1',
    payload: { tool_id: 'tool-1', name: 'find_symbol', args: { query: 'Hermes' }, context: 'Searching symbols' },
  },
  toolComplete: {
    type: 'tool.complete', session_id: 'session-1',
    payload: { tool_id: 'tool-1', name: 'find_symbol', result: { matches: 3 }, duration_s: 0.25 },
  },
  approval: {
    type: 'approval.request', session_id: 'session-1',
    payload: { command: 'dotnet test', description: 'Run tests', choices: ['once', 'session', 'always', 'deny'], allow_permanent: false },
  },
  clarify: {
    type: 'clarify.request', session_id: 'session-1',
    payload: { request_id: 'clarify-1', question: 'Which project?', choices: ['Workbench', '', 'Upstream'] },
  },
  secretRequest: {
    type: 'secret.request', session_id: 'session-1',
    payload: { request_id: 'secret-1', env_var: 'FIXTURE_API_KEY', prompt: 'Enter the fixture key', value: HERMES_CONTRACT_SENTINEL },
  },
  notificationShow: {
    type: 'notification.show',
    payload: { key: 'credits.usage', level: 'warn', kind: 'sticky', text: '⚠ Used $75 · $100 cap', extra: HERMES_CONTRACT_SENTINEL },
  },
  notificationClear: {
    type: 'notification.clear',
    payload: { key: 'credits.usage', extra: HERMES_CONTRACT_SENTINEL },
  },
  attachments: [
    { kind: 'file', label: 'notes.txt', gatewayPath: '/tmp/notes.txt', refText: '@file:/tmp/notes.txt' },
    { kind: 'image', label: 'image.png', gatewayPath: '/tmp/image.png' },
  ],
  consoleFrames: [
    { type: 'ready', profile: 'default', prompt: 'hermes> ' },
    { type: 'output', id: 3, stream: 'stdout', data: 'ok' },
    { type: 'confirm_required', command: 'cron delete 3', message: 'Delete it?' },
    { type: 'future-event', data: 'future-safe' },
  ],
  runtimeIdentity: {
    protocolVersion: 1,
    observedAtUtc: '2026-08-09T06:00:00.000Z',
    containerName: 'hermes',
    imageReference: 'nousresearch/hermes-agent:latest',
    imageId: `sha256:${'a'.repeat(64)}`,
    repoDigest: `nousresearch/hermes-agent@sha256:${'b'.repeat(64)}`,
    revision: '1234567abcdef',
    environment: HERMES_CONTRACT_SENTINEL,
  },
  mcpServers: {
    servers: [{
      name: 'serena',
      transport: 'http',
      url: 'http://host.docker.internal:9121/mcp',
      enabled: true,
      auth: null,
      tools: ['find_symbol', 'get_symbols_overview'],
      env: { SERENA_TOKEN: HERMES_CONTRACT_SENTINEL },
      private_path: HERMES_CONTRACT_SENTINEL,
    }],
  },
  mcpCatalog: {
    entries: [{
      name: 'fixture-server',
      description: 'Synthetic Nous catalog fixture',
      source: 'https://example.invalid/fixture',
      transport: 'stdio',
      auth_type: 'api_key',
      required_env: [{ name: 'FIXTURE_API_KEY', prompt: 'Fixture key', required: true }],
      command: 'uvx',
      args: ['fixture-mcp==1.0.0'],
      install_url: 'https://example.invalid/fixture.git',
      install_ref: 'fixture-ref',
      bootstrap: ['uv tool install fixture-mcp==1.0.0'],
      default_enabled: ['search'],
      post_install: 'Review the fixture permissions before enabling it.',
      needs_install: true,
      installed: false,
      enabled: false,
      secret: HERMES_CONTRACT_SENTINEL,
    }],
    diagnostics: [{ name: 'fixture-server', kind: 'warning', message: 'Synthetic diagnostic' }],
    internal_path: HERMES_CONTRACT_SENTINEL,
  },
  skills: [{
    name: 'fixture-skill',
    description: 'Synthetic compatibility skill',
    category: 'Engineering',
    enabled: true,
    provenance: 'hub',
    usage: 3,
    path: HERMES_CONTRACT_SENTINEL,
  }],
  skillHubSources: {
    sources: [{ id: 'hermes-index', label: 'Hermes Index', available: true, searchable: true }],
    index_available: true,
    featured: [{
      name: 'Fixture skill', identifier: 'official/fixture-skill', source: 'official',
      trust_level: 'builtin', repo: 'NousResearch/hermes-agent', tags: ['fixture'],
    }],
    installed: {
      'official/fixture-skill': { name: 'fixture-skill', trust_level: 'builtin', scan_verdict: 'safe' },
    },
    internal_path: HERMES_CONTRACT_SENTINEL,
  },
  skillHubScan: {
    name: 'Fixture skill', identifier: 'official/fixture-skill', source: 'official',
    trust_level: 'builtin', verdict: 'caution', summary: 'Synthetic caution', policy: 'ask',
    policy_reason: 'Review the finding',
    findings: [{ severity: 'medium', category: 'network', file: 'SKILL.md', line: 12, description: 'Synthetic network use' }],
    severity_counts: { medium: 1 }, quarantine_path: HERMES_CONTRACT_SENTINEL,
  },
  toolsets: [{
    name: 'web', label: 'Web Search', description: 'Search and extract', platform: 'cli',
    platform_label: 'CLI', enabled: true, available: true, configured: true,
    tools: ['web_search', 'web_extract'], config: HERMES_CONTRACT_SENTINEL,
  }],
  toolsetConfig: {
    name: 'web', has_category: true, active_provider: 'Brave Search',
    active_search_backend: 'brave', active_extract_backend: 'firecrawl',
    providers: [{
      name: 'Brave Search', badge: 'free', tag: 'Search only', is_active: true,
      status: 'ready', web_backend: 'brave', capabilities: ['search'],
      requires_nous_auth: false, post_setup: null,
      env_vars: [{ key: 'BRAVE_SEARCH_API_KEY', prompt: 'Brave key', url: 'https://example.invalid/key', is_set: true, value: HERMES_CONTRACT_SENTINEL }],
      internal_path: HERMES_CONTRACT_SENTINEL,
    }],
  },
} as const
