import { LANGUAGE_TOOLING_CONTRACT, type LanguageToolingProviderDescriptor } from './contracts'

export const LANGUAGE_TOOLING_PROVIDER_CATALOG = [
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'dotnet',
    label: '.NET / Roslyn',
    languages: ['csharp', 'fsharp', 'visual-basic'],
    projectKinds: ['sln', 'slnx', 'csproj', 'fsproj', 'vbproj'],
    capabilities: [
      {
        id: 'dotnet.roslyn-lsp',
        kind: 'language-server',
        label: 'Roslyn language server',
        features: ['diagnostics', 'completion', 'hover', 'definition', 'references', 'rename', 'code-actions'],
        protocol: 'lsp',
        integration: 'existing-host-reference',
        adapterKey: 'roslyn-language-server',
      },
      {
        id: 'dotnet.compiler',
        kind: 'compiler',
        label: '.NET build',
        features: ['build', 'structured-diagnostics', 'cancellation'],
        integration: 'existing-host-reference',
        adapterKey: 'dotnet-toolchain',
      },
      {
        id: 'dotnet.tests',
        kind: 'test-runner',
        label: '.NET test runner',
        features: ['test', 'structured-results', 'cancellation'],
        integration: 'host-adapter-required',
        adapterKey: 'dotnet-test-runner',
      },
      {
        id: 'dotnet.dap',
        kind: 'debug-adapter',
        label: '.NET DAP debugger',
        features: ['launch', 'breakpoints', 'continue', 'step', 'variables', 'evaluate'],
        protocol: 'dap',
        integration: 'existing-host-reference',
        adapterKey: 'dotnet-dap',
      },
    ],
  },
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'java-jdt',
    label: 'Java / Eclipse JDT',
    languages: ['java'],
    projectKinds: ['maven', 'gradle', 'java-workspace'],
    capabilities: [
      {
        id: 'java-jdt.lsp',
        kind: 'language-server',
        label: 'Eclipse JDT language server',
        features: ['diagnostics', 'completion', 'hover', 'definition', 'references', 'rename', 'code-actions'],
        protocol: 'lsp',
        integration: 'host-adapter-required',
        adapterKey: 'java-jdt-language-server',
      },
    ],
  },
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'arduino',
    label: 'Arduino',
    languages: ['arduino', 'cpp'],
    projectKinds: ['arduino-sketch'],
    capabilities: [
      {
        id: 'arduino.project',
        kind: 'project-inspection',
        label: 'Arduino project understanding',
        features: ['sketch-discovery', 'board-context', 'library-context'],
        integration: 'host-adapter-required',
        adapterKey: 'arduino-cli-project',
      },
      {
        id: 'arduino.compiler',
        kind: 'compiler',
        label: 'Arduino compiler',
        features: ['compile', 'board-selection', 'structured-diagnostics', 'cancellation'],
        integration: 'host-adapter-required',
        adapterKey: 'arduino-cli-compile',
      },
    ],
  },
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'python',
    label: 'Python',
    languages: ['python'],
    projectKinds: ['pyproject', 'python-workspace'],
    capabilities: [
      {
        id: 'python.project',
        kind: 'project-inspection',
        label: 'Python project understanding',
        features: ['source-discovery', 'package-markers', 'bounded-inspection'],
        integration: 'existing-host-reference',
        adapterKey: 'python-project-inspector',
      },
      {
        id: 'python.lsp',
        kind: 'language-server',
        label: 'Python language server',
        features: ['diagnostics', 'completion', 'hover', 'definition', 'references', 'rename'],
        protocol: 'lsp',
        integration: 'host-adapter-required',
        adapterKey: 'python-language-server',
      },
      {
        id: 'python.compiler',
        kind: 'compiler',
        label: 'Python syntax compiler',
        features: ['syntax-check', 'structured-diagnostics', 'cancellation'],
        integration: 'host-adapter-required',
        adapterKey: 'python-compiler',
      },
      {
        id: 'python.tests',
        kind: 'test-runner',
        label: 'Python test runner',
        features: ['test', 'selection', 'structured-results', 'cancellation'],
        integration: 'host-adapter-required',
        adapterKey: 'python-test-runner',
      },
    ],
  },
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'gcc',
    label: 'GNU C / C++',
    languages: ['c', 'cpp'],
    projectKinds: ['c-source', 'cpp-source', 'native-source-tree'],
    capabilities: [
      {
        id: 'gcc.compiler',
        kind: 'compiler',
        label: 'Pinned GNU C/C++ compiler',
        features: ['compile', 'structured-diagnostics', 'cancellation'],
        integration: 'existing-host-reference',
        adapterKey: 'gcc-toolchain',
      },
    ],
  },
  {
    contract: LANGUAGE_TOOLING_CONTRACT,
    id: 'raspberry-pi',
    label: 'Raspberry Pi',
    languages: ['c', 'cpp', 'python', 'shell'],
    projectKinds: ['raspberry-pi-workspace'],
    capabilities: [
      {
        id: 'raspberry-pi.inspect',
        kind: 'remote-host',
        label: 'Trusted Raspberry Pi inspection',
        features: ['probe', 'package-search', 'library-search'],
        integration: 'existing-host-reference',
        adapterKey: 'raspberry-pi-trusted-host',
      },
      {
        id: 'raspberry-pi.deploy',
        kind: 'deployment',
        label: 'Reviewed Raspberry Pi file deployment',
        features: ['single-file-deploy', 'host-key-pinning', 'explicit-approval'],
        integration: 'existing-host-reference',
        adapterKey: 'raspberry-pi-trusted-host',
      },
    ],
  },
] as const satisfies readonly LanguageToolingProviderDescriptor[]
